(in-package #:pastebin.com-api)

(defvar +pastebin-file-formats+
        '(("abap" "ABAP") 
          ("actionscript" "ActionScript") 
          ("actionscript3" "ActionScript 3") 
          ("ada" "Ada") 
          ("apache" "Apache Log") 
          ("applescript" "AppleScript") 
          ("apt_sources" "APT Sources") 
          ("asm" "ASM (NASM)") 
          ("asp" "ASP") 
          ("autoit" "AutoIt") 
          ("avisynth" "Avisynth") 
          ("bash" "Bash") 
          ("basic4gl" "Basic4GL") 
          ("bibtex" "BibTeX") 
          ("blitzbasic" "Blitz Basic") 
          ("bnf" "BNF") 
          ("boo" "BOO") 
          ("bf" "BrainFuck") 
          ("c" "C" "c" "h") 
          ("c_mac" "C for Macs") 
          ("cill" "C Intermediate Language") 
          ("csharp" "C#" "cs") 
          ("cpp" "C++" "cpp" "hpp" "cxx" "c++") 
          ("caddcl" "CAD DCL") 
          ("cadlisp" "CAD Lisp") 
          ("cfdg" "CFDG") 
          ("klonec" "Clone C") 
          ("klonecpp" "Clone C++") 
          ("cmake" "CMake") 
          ("cobol" "COBOL") 
          ("cfm" "ColdFusion") 
          ("css" "CSS") 
          ("d" "D") 
          ("dcs" "DCS") 
          ("delphi" "Delphi") 
          ("dff" "Diff") 
          ("div" "DIV") 
          ("dos" "DOS") 
          ("dot" "DOT") 
          ("eiffel" "Eiffel") 
          ("email" "Email") 
          ("erlang" "Erlang") 
          ("fo" "FO Language") 
          ("fortran" "Fortran") 
          ("freebasic" "FreeBasic") 
          ("gml" "Game Maker") 
          ("genero" "Genero") 
          ("gettext" "GetText") 
          ("groovy" "Groovy") 
          ("haskell" "Haskell" "hs") 
          ("hq9plus" "HQ9 Plus") 
          ("html4strict" "HTML" "html") 
          ("idl" "IDL") 
          ("ini" "INI file") 
          ("inno" "Inno Script") 
          ("intercal" "INTERCAL") 
          ("io" "IO") 
          ("java" "Java" "java") 
          ("java5" "Java 5") 
          ("javascript" "JavaScript" "js") 
          ("kixtart" "KiXtart") 
          ("latex" "Latex") 
          ("lsl2" "Linden Scripting") 
          ("lisp" "Lisp" "lisp" "lsp" "cl") 
          ("locobasic" "Loco Basic") 
          ("lolcode" "LOL Code") 
          ("lotusformulas" "Lotus Formulas") 
          ("lotusscript" "Lotus Script") 
          ("lscript" "LScript") 
          ("lua" "Lua") 
          ("m68k" "M68000 Assembler") 
          ("make" "Make") 
          ("matlab" "MatLab") 
          ("matlab" "MatLab") 
          ("mirc" "mIRC") 
          ("modula3" "Modula 3") 
          ("mpasm" "MPASM") 
          ("mxml" "MXML") 
          ("mysql" "MySQL") 
          ("text" "None") 
          ("nsis" "NullSoft Installer") 
          ("oberon2" "Oberon 2") 
          ("objc" "Objective C") 
          ("ocaml-brief" "OCalm Brief") 
          ("ocaml" "OCaml") 
          ("glsl" "OpenGL Shading" "cg" "fx") 
          ("oobas" "Openoffice BASIC") 
          ("oracle11" "Oracle 11") 
          ("oracle8" "Oracle 8") 
          ("pascal" "Pascal" "pas") 
          ("pawn" "PAWN") 
          ("per" "Per") 
          ("perl" "Perl" "pl") 
          ("php" "PHP" "php") 
          ("php-brief" "PHP Brief") 
          ("pic16" "Pic 16") 
          ("pixelbender" "Pixel Bender") 
          ("plsql" "PL/SQL") 
          ("povray" "POV-Ray") 
          ("powershell" "Power Shell") 
          ("progress" "Progress") 
          ("prolog" "Prolog") 
          ("properties" "Properties") 
          ("providex" "ProvideX") 
          ("python" "Python" "py") 
          ("qbasic" "QBasic") 
          ("rails" "Rails") 
          ("rebol" "REBOL") 
          ("reg" "REG") 
          ("robots" "Robots") 
          ("ruby" "Ruby" "rb") 
          ("gnuplot" "Ruby Gnuplot") 
          ("sas" "SAS") 
          ("scala" "Scala") 
          ("scheme" "Scheme" "scm") 
          ("scilab" "Scilab") 
          ("sdlbasic" "SdlBasic") 
          ("smalltalk" "Smalltalk") 
          ("smarty" "Smarty") 
          ("sql" "SQL") 
          ("tsql" "T-SQL") 
          ("tcl" "TCL" "tcl")
          ("text" "Text" "txt")
          ("teraterm" "Tera Term") 
          ("thinbasic" "thinBasic") 
          ("typoscript" "TypoScript") 
          ("unreal" "unrealScript") 
          ("vbnet" "VB.NET") 
          ("verilog" "VeriLog") 
          ("vhdl" "VHDL") 
          ("vim" "VIM" "vim") 
          ("visualprolog" "Visual Pro Log") 
          ("vb" "VisualBasic") 
          ("visualfoxpro" "VisualFoxPro") 
          ("whitespace" "WhiteSpace") 
          ("whois" "WHOIS") 
          ("winbatch" "Win Batch") 
          ("xml" "XML" "xml" "xaml") 
          ("xorg_conf" "Xorg Config") 
          ("xpp" "XPP") 
          ("z80" "Z80 Assembler")))

(defun list-available-file-formats ()
  (mapcar (lambda (spec) (copy-seq (car spec)))
          +pastebin-file-formats+))
